spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/springdb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=7761890349
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect