spring.application.name=springsecurityDemo
spring.datasource.url=jdbc:mysql://localhost:3306/user_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=7761890349
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.security.user.password=hello
jwt.secret=FnobEFhA23JVSw6+uQVPGI8yQSoilxaSNJxiiSsxYUY=

