spring.application.name=LearnSpring
spring.datasource.url=jdbc:mysql://localhost:3306/spring_crud?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=7761890349
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update





